// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgOXZzR7LnkqhjsDJDlejTinHOcGuUnw',
    appId: '1:545622238927:web:2f5901f3bdd05ae413f9ba',
    messagingSenderId: '545622238927',
    projectId: 'rowndivision-ced1a',
    authDomain: 'rowndivision-ced1a.firebaseapp.com',
    storageBucket: 'rowndivision-ced1a.appspot.com',
    measurementId: 'G-C4FTLDKN92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWbhz2V_vmeO324RAHD-z3mxeNpu5cj4',
    appId: '1:545622238927:android:b53641636e4b144e13f9ba',
    messagingSenderId: '545622238927',
    projectId: 'rowndivision-ced1a',
    storageBucket: 'rowndivision-ced1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIh3wB1kWHHG3SsA-pM4F4r6Q8UU0CU0',
    appId: '1:545622238927:ios:506e26ec3d52093d13f9ba',
    messagingSenderId: '545622238927',
    projectId: 'rowndivision-ced1a',
    storageBucket: 'rowndivision-ced1a.appspot.com',
    iosBundleId: 'com.example.rown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIh3wB1kWHHG3SsA-pM4F4r6Q8UU0CU0',
    appId: '1:545622238927:ios:506e26ec3d52093d13f9ba',
    messagingSenderId: '545622238927',
    projectId: 'rowndivision-ced1a',
    storageBucket: 'rowndivision-ced1a.appspot.com',
    iosBundleId: 'com.example.rown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgOXZzR7LnkqhjsDJDlejTinHOcGuUnw',
    appId: '1:545622238927:web:be3b12c6a66633ea13f9ba',
    messagingSenderId: '545622238927',
    projectId: 'rowndivision-ced1a',
    authDomain: 'rowndivision-ced1a.firebaseapp.com',
    storageBucket: 'rowndivision-ced1a.appspot.com',
    measurementId: 'G-4EZF5ES0NX',
  );
}
